
swagger: '2.0'

info:
  version: "0.0.1"
  title: Livi-juku asiahallinta rajapinta
  description: Tämä dokumentti sisältää Liikenneviraston asiahallintajärjestelmän rajapinnan kuvauksen juku-järjestelmälle.
  
schemes: [http]
produces: [text/plain; charset=utf-8]

paths:
  /hakemuskausi:
    post:
      description: Uuden hakemuskauden avaaminen
      parameters:
        -
          name: vuosi
          in: query
          description: Hakemuskauden vuosi
          required: true
          type: number
          format: int
          
      responses:
        200:
          description: Uusi hakemuskausi on avattu
          schema: 
            description: Hakemuskauden diaarinumero
            type: string
            
  /hakemuskausi/{diaarinumero}:   
    delete: 
      description: Hakemuskauden sulkeminen asiahallintajärjestelmään
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuskauden vuosi
          required: true
          type: number
          format: int
      responses:
        200:
          description: Hakemuskausi on suljettu
        404:
          description: Hakemuskautta {diaarinumero} ei ole olemassa
          
  /hakemus:
    post:
      consumes: [multipart/form-data]
      description: Hakija lähettää avustushakemuksen juku-järjstelmään
      parameters:
        -
          name: hakemus
          in: body
          description: Hakemuksen tiedot
          required: true
          schema: 
            $ref: '#/definitions/Hakemus'
        -
          name: dokumentti
          in: formData
          description: Avustushakemuksen dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemus on luotu
          schema: 
            description: Hakemuksen diaarinumero
            type: string
        404:
          description: Hakemuskautta {diaarinumero} ei ole olemassa
            
  /hakemus/{diaarinumero}/kasittely:
    post:
      description: Käsittelijä ottaa hakemuksen käsittelyyn
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero
          required: true
          type: string
      responses:
        200:
          description: Hakemuksen tila on käsittelyssä
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/taydennyspyynto:
    post:
      consumes: [multipart/form-data]
      description: Hakemukseen tehdään täydennyspyyntö
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero. 
          required: true
          type: string
        -
          name: täydennyspyyntö
          in: body
          description: Täydennyspyynnön sisältö 
          required: true
          schema: 
            $ref: '#/definitions/Taydennyspyynto'
        -
          name: dokumentti
          in: formData
          description: Täydennyspyynnön dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemukseen on liitetty täydennyspyyntö
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/taydennys:
    post:
      consumes: [multipart/form-data]
      description: Hakija lähettää täydennyksen hakemukseen
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero. 
          required: true
          type: string
        -
          name: täydennys
          in: body
          description: Täydennyksen sisältö 
          required: true
          schema: 
            $ref: '#/definitions/Taydennys'
        -
          name: dokumentti
          in: formData
          description: Täydennyspyynnön dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemukseen on liitetty täydennys
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/paatos:
    post:
      consumes: [multipart/form-data]
      description: Käsittelijä on mekinnyt ko. hakemuksen tarkastetuksi
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero
          required: true
          type: string
        -
          name: paatos
          in: body
          description: Päätöksen tiedot 
          required: true
          schema: 
            $ref: '#/definitions/Paatos'
        -
          name: dokumentti
          in: formData
          description: Täydennyspyynnön dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemukseen on liitetty päätös
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/maksatushakemus:
    post:
      consumes: [multipart/form-data]
      description: Käsittelijä on mekinnyt ko. hakemuksen tarkastetuksi
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero
          required: true
          type: string
        -
          name: maksatushakemus
          in: body
          description: Maksatushakemuksen tiedot 
          required: true
          schema: 
            $ref: '#/definitions/Maksatushakemus'
        -
          name: dokumentti
          in: formData
          description: Täydennyspyynnön dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemukseen on liitetty päätös
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
definitions:
  Hakemus:
    properties:
      hakemuskausi:
        type: string
        description: Hakemuskauden yksilöivä diaarinumero
      tehtäväluokka: 
        type: string
        description: Vakioteksti '07.00.01 joukkoliikenteen rahoitus'
        default: 07.00.01 joukkoliikenteen rahoitus
      menettely: 
        type: string
        description: Vakioteksti - TODO määritetään myöhemmin
      asiannimi: 
        type: string
        description: Vakioteksti 'Uusi avustushakemus'
        default: Uusi avustushakemus
      asianomistaja1: 
        type: string
        description: Vakioteksti 'Joukkoliikenteen palvelut'
        default: Joukkoliikenteen palvelut
      asianomistaja2: 
        type: string
        description: Vakioteksti 'Eskola Jenni'
        default: Eskola Jenni
      asiakirjanotsikko: 
        type: string
        description: |
          Avustushakemus_vvvv_tvv, jossa vvvv on vuosi ja tvv on hakemuksen hakijaorganisaatio 
          esim. 'Avustushakemus_2015_Tampere'
      suunta:
        type: string
        description: Vakioteksti 'saapuva'
        default: saapuva
  Taydennyspyynto:
    properties:
      nimi: 
        type: string
        description: vakio, tulee ASHAsta
      maaraaika: 
        type: string
        format: date
        description: Täydennyspyynnön määräaika, johon mennessä tähän pyyntöön pitää vastata
      kasittelija: 
        type: string
        description: Täydennyspyynnön lähettäjän nimi muodossa sukunimi etunimi, esim "Bärman Toni"
      osapuoli: 
        type: string
        description:  Vakioteksti 'Vastaanottaja'
        default: Vastaanottaja
      hakemuskausi: 
        type: string
        description: |
          Hakemuskauden yksilöivä diaarinumero 
          TODO tälle ei pitäisi olla tarvetta hakemus kuuluu jo valmiiksi aina johonkin kauteen
      suunta: 
        type: string
        description:  Vakioteksti 'lähtevä'
        default: lähtevä
  Taydennys:
    properties:
      nimi: 
        type: string
        description: vakio, tulee ASHAsta
      käsittelijä: 
        type: string
        description: täydennyspyynnön lähettäjä, esim "Bärman Toni" 
      osapuoli:  
        type: string
        description: Vakioteksti 'Lähettäjä'
        default: Lähettäjä
      asiakirjanotsikko: 
        type: string
        description: ??? TODO
      hakemuskausi:  
        type: string
        description: Hakemuskauden yksilöivä diaarinumero
      suunta:   
        type: string
        description: Vakioteksti 'saapuva'
        default: saapuva
  Paatos:
    properties:
      asiakirjanotsikko: 
        type: string
        description: ??? TODO
  Maksatushakemus:
    properties:
      asiannimi: 
        type: string
        description: vakioteksti 'Uusi maksatushakemus'
        default: Uusi maksatushakemus
      käsittelijä: 
        type: string
        description:  tähän liittyvän avustushakemuksen käsittelijän nimi
      osapuoli:  
        type: string
        description: Vakioteksti 'Lähettäjä'
        default: Lähettäjä
      hakemuskausi: 
        type: string
        description: Hakemuskauden yksilöivä diaarinumero
      suunta:
        type: string
        description: Vakioteksti 'saapuva'
        default: saapuva
      asiakirjanotsikko:  
        type: string
        description: ??? TODO
    

  

      