
swagger: '2.0'

info:
  version: "0.0.3"
  title: Livi-juku asiahallinta rajapinta
  description: 
    Tämä dokumentti sisältää Liikenneviraston asiahallintajärjestelmän rajapinnan kuvauksen juku-järjestelmälle.
    Rajapintakuvaus perustuu dokumenttiin Integraatiopalvelukuvaus JUKU-ASHA (23.2.15).
  
schemes: [http]
produces: [text/plain; charset=utf-8]

paths:
  /hakemuskausi:
    post:
      consumes: [multipart/form-data]
      description: Uuden hakemuskauden avaaminen
      parameters:
        -
          name: hakemuskausi
          in: body
          description: Hakemuskauden tiedot
          required: true
          schema: 
            $ref: '#/definitions/Hakemuskausi'
        -
          name: hakuohje-asiakirja
          in: formData
          description: Hakemuskauden hakuohje (pdf/a)
          required: true
          type: file  
      responses:
        200:
          description: Uusi hakemuskausi on avattu
          schema: 
            description: Hakemuskauden diaarinumero
            type: string
            
  /hakemuskausi/{diaarinumero}/sulje:   
    put: 
      description: Hakemuskauden sulkeminen asiahallintajärjestelmään
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuskauden diaarinumero
          required: true
          type: number
          format: int
      responses:
        200:
          description: Hakemuskausi on suljettu
        404:
          description: Hakemuskautta {diaarinumero} ei ole olemassa
          
  /hakemus:
    post:
      consumes: [multipart/form-data]
      description: 
        Hakija lähettää avustushakemuksen juku-järjstelmään. 
        Hakemus-asiakirjan lisäksi tässä pyynnössä voi tulla 
        mukana n kpl hakemuksen liitedokumentteja omina multipart-osioina.
      parameters:
        -
          name: hakemus
          in: body
          description: Hakemuksen tiedot
          required: true
          schema: 
            $ref: '#/definitions/Hakemus'
        -
          name: hakemus-asiakirja
          in: formData
          description: Avustushakemuksen dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemus on luotu
          schema: 
            description: Hakemuksen diaarinumero
            type: string
        404:
          description: Hakemuskautta {diaarinumero} ei ole olemassa
            
  /hakemus/{diaarinumero}/kasittely:
    put:
      description: Käsittelijä ottaa hakemuksen käsittelyyn
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero
          required: true
          type: string
      responses:
        200:
          description: Hakemuksen tila on käsittelyssä
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/tarkastettu:
    put:
      description: Käsittelijä ottaa hakemuksen käsittelyyn
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero
          required: true
          type: string
      responses:
        200:
          description: Hakemuksen tila on tarkastettu
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/taydennyspyynto:
    post:
      description: Hakemukseen tehdään täydennyspyyntö
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero. 
          required: true
          type: string
        -
          name: täydennyspyyntö
          in: body
          description: Täydennyspyynnön sisältö 
          required: true
          schema: 
            $ref: '#/definitions/Taydennyspyynto'
      responses:
        200:
          description: Hakemukseen on liitetty täydennyspyyntö
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/taydennys:
    post:
      consumes: [multipart/form-data]
      description: 
        Hakija lähettää täydennyksen hakemukseen. 
        Hakemus-asiakirjan lisäksi tässä pyynnössä voi tulla 
        mukana n kpl hakemuksen liitedokumentteja omina multipart-osioina.
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero. 
          required: true
          type: string
        -
          name: täydennys
          in: body
          description: Täydennyksen sisältö 
          required: true
          schema: 
            $ref: '#/definitions/Taydennys'
        -
          name: hakemus-asiakirja
          in: formData
          description: Täydennetty hakemus dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemukseen on liitetty täydennys
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/paatos:
    post:
      consumes: [multipart/form-data]
      description: Hakemukseen on tehty päätös.
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero
          required: true
          type: string
        -
          name: asiakirja
          in: formData
          description: Päätösdokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Hakemukseen on liitetty päätös
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
  /hakemus/{diaarinumero}/maksatushakemus:
    post:
      consumes: [multipart/form-data]
      description: 
        Hakija lähettää maksatushakemuksen juku-järjstelmään. 
        Hakemus-asiakirjan lisäksi tässä pyynnössä voi tulla 
        mukana n kpl hakemuksen liitedokumentteja omina multipart-osioina.
      parameters:
        -
          name: diaarinumero
          in: path
          description: Hakemuksen diaarinumero. 
          required: true
          type: string
        -
          name: maksatushakemus
          in: body
          description: Maksatushakemuksen tiedot 
          required: true
          schema: 
            $ref: '#/definitions/Taydennys'
        -
          name: hakemus-asiakirja
          in: formData
          description: Maksatushakemuksen dokumentti (pdf/a)
          required: true
          type: file
      responses:
        200:
          description: Uusi maksatushakemus on tallennettu asiahallintaan
        404:
          description: Hakemusta {diaarinumero} ei ole olemassa
          
definitions:
  Hakemuskausi:
    properties:
      asianNimi: 
        type: string
        description: 
          Vapaamuotoinen tekstikenttä, johon tulee teksti 
          "Hakemuskausi {hakemuskauden vuosi}" esim. "Hakemuskausi 2016"
      omistavaOrganisaatio: 
        type: string
        description: Kauden avanneen käyttäjän organisaatio
      omistavaHenkilo: 
        type: string
        description: Kauden (JUKUn käyttöliittymästä) avannut käyttäjä
  Hakemus:
    properties:
      kausi:
        type: string
        description: Hakemuskauden yksilöivä diaarinumero
      omistavaOrganisaatio: 
        type: string
        description: Kauden avanneen käyttäjän organisaatio
      omistavaHenkilo: 
        type: string
        description: Kauden (JUKUn käyttöliittymästä) avannut käyttäjä
  Taydennyspyynto:
    properties:
      maaraaika: 
        type: string
        format: date
        description: Täydennyspyynnön määräaika (minuutin tarkkuudella), johon mennessä tähän pyyntöön pitää vastata
      kasittelija: 
        type: string
        description: Hakemuksen käsittelijän nimi muodossa sukunimi etunimi, esim "Bärman Toni".
  Taydennys:
    properties:
      käsittelijä: 
        type: string
        description: 
          Hakemuksen käsittelijän nimi muodossa sukunimi etunimi, esim "Bärman Toni".
